steps:
  - name: maven:3.8.4-openjdk-11
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/transactionservice', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/transactionservice']
    # deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=deployment.yaml
      - --image=gcr.io/$PROJECT_ID/transactionservice
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

timeout: '1200s' # Adjust as needed

logsBucket: 'gs://rtb-cloud-build' # Specify your logs bucket here

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
