apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: "paymentservice"
  namespace: "rtb"
  labels:
    app: "paymentservice"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "paymentservice"
  template:
    metadata:
      labels:
        app: "paymentservice"
    spec:
      containers:
        - name: "paymentservice-1"
          image: "gcr.io/gcp-rtb-429519/paymentservice:latest"
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "paymentservice-svc"
  namespace: "rtb"
spec:
  #type: "ClusterIP"
  type: "NodePort"
  selector:
    app: "paymentservice"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8083
      nodePort: 30063
      
