apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "productservice"
  namespace: "rtb"
  labels:
    app: "productservice"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "productservice"
  template:
    metadata:
      labels:
        app: "productservice"
    spec:
      containers:
        - name: "productservice-1"
          image: "gcr.io/gcp-rtb-429519/productservice:latest"
          ports:
            - containerPort: 8083
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "prod"
          volumeMounts:
            - name: "productservice-storage"
              mountPath: "/data"
  volumeClaimTemplates:
    - metadata:
        name: "productservice-storage"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
  updateStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      partition: 0
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "productservice-svc"
  namespace: "rtb"
  labels:
    app: "productservice"
spec:
  #type: "ClusterIP"
  type: "NodePort"
  selector:
    app: "productservice"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8083
      nodePort: 30061
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "productservice-hpa"
  namespace: "rtb"
  labels:
    app: "productservice"
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "StatefulSet"
    name: "productservice"
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 50