CREATE TABLE Payment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_ID  INT NOT NULL,
    PAYMENT_STATUS VARCHAR(50) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    TRANSACTIONID int,
    PRIMARY KEY (id)
);
